# roleplay_scenarios.py
# 롤플레잉 시뮬레이션 시나리오 데이터 (확장판 - 105개)

SCENARIO_CATEGORIES = [
    "좌석 관련",
    "기내 서비스",
    "안전/규정",
    "불만/컴플레인",
    "의료/응급",
    "특수 승객",
    "승객 간 갈등",
]

# 시나리오 데이터
# difficulty: 1~4 (별 개수)
# keywords: 평가 시 체크할 핵심 포인트
SCENARIOS = {
    # ========== 좌석 관련 (15개) ==========
    "seat_change_full": {
        "category": "좌석 관련",
        "title": "만석인데 좌석 변경 요청",
        "difficulty": 2,
        "situation": "장거리 비행 중, 만석 상황입니다. 중년 여성 승객이 창가 좌석을 원한다며 좌석 변경을 요청합니다.",
        "passenger_mood": "정중하지만 기대감이 큼",
        "passenger_persona": "50대 여성, 해외여행이 처음이라 창가에서 풍경을 보고 싶어함",
        "escalation_triggers": ["계속 거절만 할 경우", "대안 없이 안 된다고만 할 경우"],
        "ideal_response_keywords": ["공감", "대안 제시", "다른 승객 협조 요청 시도"],
        "evaluation_criteria": {
            "empathy": "승객의 기대감에 공감했는가",
            "alternative": "가능한 대안을 제시했는가",
            "manner": "정중하고 친절하게 응대했는가",
        },
    },
    "snoring_complaint": {
        "category": "좌석 관련",
        "title": "옆자리 승객 코골이 불만",
        "difficulty": 2,
        "situation": "야간 비행 중, 한 승객이 옆자리 승객의 심한 코골이로 잠을 못 자겠다며 불만을 제기합니다. 만석입니다.",
        "passenger_mood": "피곤하고 짜증난 상태",
        "passenger_persona": "30대 직장인, 내일 중요한 미팅이 있어서 꼭 자야 함",
        "escalation_triggers": ["아무 조치도 안 할 경우", "참으라고만 할 경우"],
        "ideal_response_keywords": ["양측 배려", "귀마개/안대 제공", "가능한 좌석 확인"],
        "evaluation_criteria": {
            "empathy": "승객의 불편함에 공감했는가",
            "solution": "실질적인 해결책을 제시했는가",
            "balance": "양측 승객 모두 배려했는가",
        },
    },
    "emergency_exit_english": {
        "category": "좌석 관련",
        "title": "비상구 좌석인데 영어 못함",
        "difficulty": 3,
        "situation": "비상구 좌석에 앉은 승객이 영어를 전혀 못합니다. 규정상 비상구 좌석은 영어 의사소통이 가능해야 합니다.",
        "passenger_mood": "왜 문제인지 이해 못함, 좌석 좋아서 기분 좋음",
        "passenger_persona": "60대 남성, 다리 불편해서 넓은 좌석 원함, 영어 전혀 못함",
        "escalation_triggers": ["무조건 이동하라고 할 경우", "이유 설명 없이 강요할 경우"],
        "ideal_response_keywords": ["규정 설명", "안전 이유 설명", "대체 좌석 제안", "정중한 요청"],
        "evaluation_criteria": {
            "regulation": "안전 규정을 명확히 설명했는가",
            "respect": "승객의 자존심을 배려했는가",
            "alternative": "대체 좌석을 제안했는가",
        },
    },
    "family_separated": {
        "category": "좌석 관련",
        "title": "가족인데 좌석이 떨어짐",
        "difficulty": 2,
        "situation": "어린 자녀(7살)와 함께 탑승한 엄마가 좌석이 떨어져 배정되었다며 도움을 요청합니다.",
        "passenger_mood": "걱정되고 불안함",
        "passenger_persona": "30대 엄마, 아이가 처음 비행기 타서 옆에 있어야 함",
        "escalation_triggers": ["방법이 없다고만 할 경우", "본인이 알아서 하라고 할 경우"],
        "ideal_response_keywords": ["다른 승객 협조 요청", "적극적 해결 시도", "안심시키기"],
        "evaluation_criteria": {
            "proactive": "적극적으로 해결하려 했는가",
            "empathy": "엄마의 불안감에 공감했는가",
            "effort": "다른 승객에게 협조를 구했는가",
        },
    },
    "upgrade_demand": {
        "category": "좌석 관련",
        "title": "비즈니스 업그레이드 요구",
        "difficulty": 3,
        "situation": "이코노미 승객이 '자주 이용하는 고객'이라며 비즈니스 클래스로 무료 업그레이드를 강력히 요구합니다.",
        "passenger_mood": "자신감 있고 당당함, 거절 시 불쾌해함",
        "passenger_persona": "40대 사업가, VIP 대우받는 것에 익숙함",
        "escalation_triggers": ["단호하게 거절만 할 경우", "무시하는 듯한 태도"],
        "ideal_response_keywords": ["정중한 거절", "마일리지 안내", "감사 표현", "대안 제시"],
        "evaluation_criteria": {
            "firmness": "원칙을 지키며 거절했는가",
            "politeness": "정중하게 응대했는가",
            "alternative": "가능한 대안을 제시했는가",
        },
    },
    "bassinet_seat_conflict": {
        "category": "좌석 관련",
        "title": "배시넷 좌석 중복 예약",
        "difficulty": 3,
        "situation": "두 가족이 모두 배시넷(아기 침대) 좌석을 예약했다고 주장합니다. 하지만 배시넷은 하나뿐입니다.",
        "passenger_mood": "양측 모두 긴장, 포기 안 함",
        "passenger_persona": "양측 모두 6개월 미만 아기를 안은 엄마",
        "escalation_triggers": ["한쪽 편만 들 경우", "먼저 온 사람이라고만 할 경우"],
        "ideal_response_keywords": ["예약 확인", "공정한 해결", "대안 제시", "양측 배려"],
        "evaluation_criteria": {
            "fairness": "공정하게 판단했는가",
            "solution": "대안을 제시했는가",
            "calm": "양측을 진정시켰는가",
        },
    },
    "legroom_extra_fee": {
        "category": "좌석 관련",
        "title": "좌석 추가요금 환불 요구",
        "difficulty": 2,
        "situation": "앞자리가 비어있는데 자기 좌석보다 넓어 보인다며 추가요금을 냈으니 환불해달라고 합니다.",
        "passenger_mood": "억울함, 속았다는 느낌",
        "passenger_persona": "20대 남성, 학생이라 비용에 민감함",
        "escalation_triggers": ["안 된다고만 할 경우", "규정만 말할 경우"],
        "ideal_response_keywords": ["공감", "좌석 차이 설명", "정중한 거절", "서비스 제공 제안"],
        "evaluation_criteria": {
            "empathy": "승객의 마음을 이해했는가",
            "explanation": "합리적으로 설명했는가",
            "alternative": "다른 혜택을 제안했는가",
        },
    },
    "seat_recline_broken": {
        "category": "좌석 관련",
        "title": "좌석 리클라인 고장",
        "difficulty": 2,
        "situation": "장거리 비행인데 좌석 리클라이닝이 작동하지 않습니다. 승객이 화를 내며 자리를 바꿔달라고 합니다.",
        "passenger_mood": "화남, 불편함",
        "passenger_persona": "40대 남성, 허리가 안 좋아서 눕지 못하면 힘듦",
        "escalation_triggers": ["빈자리가 없다고만 할 경우", "고장을 대수롭지 않게 여길 경우"],
        "ideal_response_keywords": ["사과", "좌석 확인", "쿠션/베개 제공", "보상 언급"],
        "evaluation_criteria": {
            "apology": "진심으로 사과했는가",
            "solution": "대안을 적극 찾았는가",
            "compensation": "보상을 언급했는가",
        },
    },
    "window_shade_fight": {
        "category": "좌석 관련",
        "title": "창문 가리개 분쟁",
        "difficulty": 1,
        "situation": "창가 승객이 창문을 열고 싶어하는데 옆 승객이 눈이 부시니 닫아달라고 합니다.",
        "passenger_mood": "양측 불만",
        "passenger_persona": "창가: 구름 사진 찍고 싶은 20대 / 옆: 자려고 하는 40대",
        "escalation_triggers": ["한쪽 편만 들 경우"],
        "ideal_response_keywords": ["양측 배려", "타협점 제시", "안대 제공"],
        "evaluation_criteria": {
            "balance": "양측을 모두 배려했는가",
            "solution": "절충안을 제시했는가",
            "diplomacy": "외교적으로 해결했는가",
        },
    },
    "wrong_seat_class": {
        "category": "좌석 관련",
        "title": "클래스 착각 (이코노미가 비즈니스인 줄)",
        "difficulty": 2,
        "situation": "승객이 비즈니스석에 앉아있는데 티켓을 확인하니 이코노미입니다. 승객은 비즈니스를 샀다고 주장합니다.",
        "passenger_mood": "혼란, 당황, 약간의 분노",
        "passenger_persona": "50대 여성, 여행사 통해 예약함",
        "escalation_triggers": ["무조건 이동하라고 할 경우", "창피를 줄 경우"],
        "ideal_response_keywords": ["조용히 처리", "티켓 재확인", "정중한 안내", "자존심 배려"],
        "evaluation_criteria": {
            "discretion": "다른 승객 앞에서 창피 안 주었는가",
            "verification": "티켓을 정확히 확인했는가",
            "manner": "정중하게 안내했는가",
        },
    },
    "aisle_seat_toilet": {
        "category": "좌석 관련",
        "title": "화장실 자주 가서 통로석 원함",
        "difficulty": 2,
        "situation": "창가 좌석 승객이 건강 문제로 화장실을 자주 가야 한다며 통로석으로 바꿔달라고 요청합니다.",
        "passenger_mood": "불안함, 부끄러움",
        "passenger_persona": "60대 남성, 전립선 문제가 있음",
        "escalation_triggers": ["안 된다고만 할 경우", "이유를 캐물을 경우"],
        "ideal_response_keywords": ["프라이버시 존중", "다른 승객 협조", "최대한 배려"],
        "evaluation_criteria": {
            "privacy": "건강 문제를 배려했는가",
            "effort": "좌석 변경을 위해 노력했는가",
            "respect": "존중하는 태도를 보였는가",
        },
    },
    "honeymoon_seat_request": {
        "category": "좌석 관련",
        "title": "신혼부부 붙여달라고 요청",
        "difficulty": 1,
        "situation": "신혼여행 가는 커플이 좌석이 떨어져 배정되었다며 꼭 붙여달라고 합니다.",
        "passenger_mood": "기대감, 약간의 걱정",
        "passenger_persona": "20대 신혼부부, 첫 해외여행",
        "escalation_triggers": ["무심하게 대할 경우"],
        "ideal_response_keywords": ["축하 인사", "적극적 도움", "다른 승객 협조"],
        "evaluation_criteria": {
            "warmth": "따뜻하게 응대했는가",
            "effort": "적극적으로 도왔는가",
            "success": "문제를 해결했는가",
        },
    },
    "seat_dirty": {
        "category": "좌석 관련",
        "title": "좌석이 더럽다 (이전 승객 흔적)",
        "difficulty": 2,
        "situation": "승객이 좌석에 음식물 얼룩과 과자 부스러기가 있다며 불쾌해합니다.",
        "passenger_mood": "역겨움, 불쾌함",
        "passenger_persona": "30대 여성, 청결에 민감함",
        "escalation_triggers": ["가볍게 여길 경우", "본인이 닦으라고 할 경우"],
        "ideal_response_keywords": ["즉시 사과", "직접 청소", "다른 좌석 제안", "물티슈 제공"],
        "evaluation_criteria": {
            "apology": "진심으로 사과했는가",
            "action": "즉시 조치를 취했는가",
            "solution": "깨끗하게 해결했는가",
        },
    },
    "exit_row_pregnant": {
        "category": "좌석 관련",
        "title": "임산부가 비상구석에 앉음",
        "difficulty": 3,
        "situation": "비상구 좌석에 임신 7개월로 보이는 승객이 앉아있습니다. 규정상 비상구 좌석 착석이 불가합니다.",
        "passenger_mood": "편하게 앉고 싶음, 규정 모름",
        "passenger_persona": "30대 임산부, 다리 붓기로 넓은 자리 원함",
        "escalation_triggers": ["강압적으로 이동시킬 경우", "이유 없이 강요할 경우"],
        "ideal_response_keywords": ["안전 이유 설명", "건강 배려", "편한 대체 좌석 제안", "정중함"],
        "evaluation_criteria": {
            "explanation": "규정 이유를 잘 설명했는가",
            "care": "임산부를 배려했는가",
            "alternative": "좋은 대체 좌석을 제안했는가",
        },
    },
    "last_minute_seat_change": {
        "category": "좌석 관련",
        "title": "출발 직전 좌석 변경 요청",
        "difficulty": 2,
        "situation": "문이 닫히기 직전 승객이 갑자기 다른 좌석으로 바꿔달라고 합니다. 곧 출발해야 합니다.",
        "passenger_mood": "급함, 강하게 요청",
        "passenger_persona": "40대 사업가, 전화 통화하다 늦게 요청",
        "escalation_triggers": ["무조건 안 된다고 할 경우"],
        "ideal_response_keywords": ["상황 설명", "출발 후 확인 약속", "안전 우선 설명"],
        "evaluation_criteria": {
            "professionalism": "전문적으로 대응했는가",
            "safety": "안전과 스케줄을 우선했는가",
            "promise": "착륙 후 도움을 약속했는가",
        },
    },

    # ========== 기내 서비스 (15개) ==========
    "special_meal_missing": {
        "category": "기내 서비스",
        "title": "특별식 예약했는데 없음",
        "difficulty": 3,
        "situation": "채식 특별식을 예약한 승객에게 해당 식사가 누락되었습니다. 승객은 종교적 이유로 일반식을 먹을 수 없습니다.",
        "passenger_mood": "당황하고 화남",
        "passenger_persona": "40대 인도인, 힌두교 신자로 소고기 절대 불가",
        "escalation_triggers": ["일반식이라도 드시라고 할 경우", "사과 없이 변명만 할 경우"],
        "ideal_response_keywords": ["진심 어린 사과", "대안 찾기", "과일/빵 등 제공", "보상 언급"],
        "evaluation_criteria": {
            "apology": "진심으로 사과했는가",
            "solution": "먹을 수 있는 대안을 찾았는가",
            "compensation": "적절한 보상을 언급했는가",
        },
    },
    "foreign_object_food": {
        "category": "기내 서비스",
        "title": "음식에 이물질 발견",
        "difficulty": 4,
        "situation": "승객이 기내식에서 머리카락을 발견했다며 화를 내고 있습니다.",
        "passenger_mood": "매우 화남, 역겨워함",
        "passenger_persona": "30대 여성, 위생에 민감함, SNS 활발히 함",
        "escalation_triggers": ["변명할 경우", "대수롭지 않게 여길 경우"],
        "ideal_response_keywords": ["즉시 사과", "음식 교체", "진정성", "보상 제안"],
        "evaluation_criteria": {
            "immediate_action": "즉시 음식을 치우고 사과했는가",
            "sincerity": "진정성 있는 태도를 보였는가",
            "compensation": "적절한 보상을 제안했는가",
        },
    },
    "drunk_more_alcohol": {
        "category": "기내 서비스",
        "title": "술 더 달라 (이미 취함)",
        "difficulty": 3,
        "situation": "이미 상당히 취한 승객이 술을 더 달라고 요청합니다. 말이 어눌하고 얼굴이 붉습니다.",
        "passenger_mood": "기분 좋게 취함, 거절 시 짜증",
        "passenger_persona": "50대 남성, 휴가 기분으로 기분 좋음",
        "escalation_triggers": ["무조건 안 된다고 할 경우", "취했다고 직접 말할 경우"],
        "ideal_response_keywords": ["안전 이유 설명", "부드러운 거절", "물/음료 대안", "자존심 배려"],
        "evaluation_criteria": {
            "safety": "안전을 이유로 거절했는가",
            "dignity": "승객의 자존심을 배려했는가",
            "alternative": "다른 음료를 권했는가",
        },
    },
    "duty_free_soldout": {
        "category": "기내 서비스",
        "title": "면세품 품절 불만",
        "difficulty": 2,
        "situation": "승객이 원하던 면세품이 품절되어 화를 내고 있습니다. 선물용으로 꼭 필요했다고 합니다.",
        "passenger_mood": "실망하고 짜증남",
        "passenger_persona": "40대 여성, 시어머니 선물로 꼭 필요했음",
        "escalation_triggers": ["품절이니 어쩔 수 없다고만 할 경우"],
        "ideal_response_keywords": ["공감", "대안 상품 추천", "도착지 면세점 안내"],
        "evaluation_criteria": {
            "empathy": "실망감에 공감했는가",
            "alternative": "대안을 제시했는가",
            "helpfulness": "도움이 되려는 태도를 보였는가",
        },
    },
    "blanket_shortage": {
        "category": "기내 서비스",
        "title": "담요/베개 부족",
        "difficulty": 1,
        "situation": "추위를 많이 타는 승객이 담요를 요청했는데 재고가 부족합니다.",
        "passenger_mood": "춥고 불편함",
        "passenger_persona": "60대 여성, 냉방에 약함",
        "escalation_triggers": ["없다고만 할 경우"],
        "ideal_response_keywords": ["대안 찾기", "다른 승객 반납 확인", "에어컨 조절 제안"],
        "evaluation_criteria": {
            "effort": "담요를 찾으려 노력했는가",
            "alternative": "대안을 제시했는가",
            "care": "승객을 배려하는 태도를 보였는가",
        },
    },
    "coffee_spill": {
        "category": "기내 서비스",
        "title": "승무원이 커피 쏟음",
        "difficulty": 4,
        "situation": "난기류로 인해 커피를 승객에게 쏟았습니다. 승객의 흰색 셔츠에 얼룩이 생겼습니다.",
        "passenger_mood": "놀람, 화남",
        "passenger_persona": "40대 남성 사업가, 중요한 미팅 가는 길",
        "escalation_triggers": ["변명할 경우", "가볍게 여길 경우"],
        "ideal_response_keywords": ["즉시 사과", "응급 처치", "드라이클리닝 보상", "옷 제공 가능 확인"],
        "evaluation_criteria": {
            "immediate": "즉시 대응했는가",
            "apology": "진심으로 사과했는가",
            "compensation": "보상 방안을 제시했는가",
        },
    },
    "kid_meal_allergy": {
        "category": "기내 서비스",
        "title": "아이 음식 알레르기 (견과류)",
        "difficulty": 4,
        "situation": "아이가 기내식을 먹다가 엄마가 견과류가 있다며 급하게 멈춥니다. 아이는 견과류 알레르기가 있습니다.",
        "passenger_mood": "공포, 급박함",
        "passenger_persona": "30대 엄마와 8살 아이, 심한 알레르기 병력",
        "escalation_triggers": ["늦게 대응할 경우"],
        "ideal_response_keywords": ["즉시 확인", "의료킷 준비", "의사 호출", "안심시키기"],
        "evaluation_criteria": {
            "speed": "신속하게 대응했는가",
            "medical": "알레르기 대응 절차를 따랐는가",
            "calm": "상황을 침착하게 관리했는가",
        },
    },
    "meal_choice_gone": {
        "category": "기내 서비스",
        "title": "원하는 기내식 선택지 없음",
        "difficulty": 1,
        "situation": "비프가 먹고 싶었는데 치킨만 남았다며 승객이 불만을 표시합니다.",
        "passenger_mood": "실망, 짜증",
        "passenger_persona": "50대 남성, 비행이 지루해서 기내식이 유일한 낙이었음",
        "escalation_triggers": ["어쩔 수 없다고만 할 경우"],
        "ideal_response_keywords": ["사과", "추가 간식 제공", "음료 서비스", "다음 식사 우선권"],
        "evaluation_criteria": {
            "empathy": "실망감을 이해했는가",
            "compensation": "대안을 제시했는가",
            "service": "추가 서비스를 제공했는가",
        },
    },
    "hot_water_request": {
        "category": "기내 서비스",
        "title": "분유용 뜨거운 물 요청",
        "difficulty": 1,
        "situation": "아기 분유를 타야 한다며 뜨거운 물을 요청합니다.",
        "passenger_mood": "급함, 아기가 울음",
        "passenger_persona": "20대 엄마, 6개월 아기와 함께",
        "escalation_triggers": ["늦게 가져다줄 경우"],
        "ideal_response_keywords": ["신속한 대응", "적정 온도 확인", "도움 제안"],
        "evaluation_criteria": {
            "speed": "빠르게 대응했는가",
            "safety": "안전한 온도인지 확인했는가",
            "care": "추가 도움을 제안했는가",
        },
    },
    "headphone_broken": {
        "category": "기내 서비스",
        "title": "헤드폰이 안 됨",
        "difficulty": 1,
        "situation": "승객이 영화를 보려는데 헤드폰이 작동하지 않는다며 교체를 요청합니다.",
        "passenger_mood": "약간 짜증",
        "passenger_persona": "20대 여성, 긴 비행이 지루함",
        "escalation_triggers": ["늦게 대응할 경우", "재고가 없다고만 할 경우"],
        "ideal_response_keywords": ["즉시 교체", "사과", "작동 확인"],
        "evaluation_criteria": {
            "speed": "빠르게 교체했는가",
            "service": "정상 작동하는지 확인했는가",
            "attitude": "친절하게 응대했는가",
        },
    },
    "baby_food_warm": {
        "category": "기내 서비스",
        "title": "이유식 데워달라",
        "difficulty": 1,
        "situation": "승객이 가져온 이유식을 데워달라고 요청합니다.",
        "passenger_mood": "부탁하는 상태",
        "passenger_persona": "30대 엄마, 10개월 아기",
        "escalation_triggers": ["안 된다고 할 경우"],
        "ideal_response_keywords": ["친절히 수락", "적정 온도", "안전 확인 부탁"],
        "evaluation_criteria": {
            "willingness": "기꺼이 도왔는가",
            "safety": "온도를 확인해달라고 안내했는가",
            "care": "아기와 엄마를 배려했는가",
        },
    },
    "wifi_not_working": {
        "category": "기내 서비스",
        "title": "유료 와이파이 안 됨",
        "difficulty": 2,
        "situation": "유료로 와이파이를 구매했는데 계속 끊긴다며 환불을 요구합니다.",
        "passenger_mood": "화남, 억울함",
        "passenger_persona": "30대 직장인, 급한 업무 메일 때문에 구매함",
        "escalation_triggers": ["기술적 문제라고만 할 경우"],
        "ideal_response_keywords": ["사과", "환불 절차 안내", "다른 해결 시도", "공감"],
        "evaluation_criteria": {
            "empathy": "불편함에 공감했는가",
            "solution": "환불 방법을 안내했는가",
            "effort": "문제 해결을 시도했는가",
        },
    },
    "ice_cream_request": {
        "category": "기내 서비스",
        "title": "아이스크림 언제 나오냐",
        "difficulty": 1,
        "situation": "아이가 기내에서 나눠주는 아이스크림을 기다리고 있는데 아직 서비스 전입니다.",
        "passenger_mood": "아이가 기대에 차 있음",
        "passenger_persona": "5살 여아와 엄마",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["서비스 시간 안내", "친절한 설명", "기대감 유지"],
        "evaluation_criteria": {
            "kindness": "아이에게 친절했는가",
            "information": "정확한 정보를 제공했는가",
            "warmth": "따뜻하게 응대했는가",
        },
    },
    "seat_screen_broken": {
        "category": "기내 서비스",
        "title": "개인 스크린 고장",
        "difficulty": 2,
        "situation": "좌석 스크린이 작동하지 않습니다. 장거리 비행이라 승객이 불만입니다.",
        "passenger_mood": "짜증, 지루함 예상",
        "passenger_persona": "20대 남성, 영화 많이 보려고 했음",
        "escalation_triggers": ["고칠 수 없다고만 할 경우", "아무 조치도 안 할 경우"],
        "ideal_response_keywords": ["사과", "리셋 시도", "좌석 변경", "잡지/신문 제공"],
        "evaluation_criteria": {
            "troubleshoot": "해결을 시도했는가",
            "alternative": "대안을 제시했는가",
            "compensation": "불편에 대한 배려를 했는가",
        },
    },
    "medicine_request": {
        "category": "기내 서비스",
        "title": "두통약 요청",
        "difficulty": 1,
        "situation": "승객이 두통이 있다며 두통약을 요청합니다.",
        "passenger_mood": "아픔, 불편함",
        "passenger_persona": "40대 여성",
        "escalation_triggers": ["없다고만 할 경우"],
        "ideal_response_keywords": ["약 제공", "물 제공", "상태 확인", "추가 도움 제안"],
        "evaluation_criteria": {
            "help": "약을 제공했는가",
            "care": "상태를 확인했는가",
            "follow_up": "이후에도 신경 썼는가",
        },
    },

    # ========== 안전/규정 (15개) ==========
    "takeoff_restroom": {
        "category": "안전/규정",
        "title": "이륙 중 화장실 가겠다",
        "difficulty": 3,
        "situation": "이륙을 위해 활주로에 진입했는데 승객이 급하게 화장실을 가야 한다며 일어나려 합니다.",
        "passenger_mood": "급박함, 참기 힘들어함",
        "passenger_persona": "20대 남성, 배탈이 났는지 얼굴이 창백함",
        "escalation_triggers": ["무조건 안 된다고만 할 경우", "공감 없이 규정만 말할 경우"],
        "ideal_response_keywords": ["안전 규정 설명", "공감 표현", "이륙 후 바로 안내 약속", "최대한 빨리"],
        "evaluation_criteria": {
            "safety": "안전 규정을 명확히 설명했는가",
            "empathy": "승객의 급박함에 공감했는가",
            "promise": "이륙 후 즉시 안내를 약속했는가",
        },
    },
    "electronics_refuse": {
        "category": "안전/규정",
        "title": "전자기기 끄기 거부",
        "difficulty": 3,
        "situation": "이륙 준비 중 한 승객이 노트북을 끄지 않고 계속 업무를 보고 있습니다. 두 번 요청했지만 '중요한 일'이라며 거부합니다.",
        "passenger_mood": "바쁘고 짜증남",
        "passenger_persona": "30대 직장인, 급한 업무 마감 중",
        "escalation_triggers": ["계속 부드럽게만 요청할 경우", "포기하고 넘어갈 경우"],
        "ideal_response_keywords": ["단호한 태도", "법적 규정 언급", "착륙 후 시간 약속", "안전 강조"],
        "evaluation_criteria": {
            "firmness": "단호하게 요청했는가",
            "regulation": "규정/법적 근거를 설명했는가",
            "professionalism": "감정적이지 않고 전문적이었는가",
        },
    },
    "oversized_luggage": {
        "category": "안전/규정",
        "title": "큰 수하물 선반에 안 들어감",
        "difficulty": 2,
        "situation": "승객의 기내 수하물이 너무 커서 선반에 들어가지 않습니다. 승객은 위탁하기 싫어합니다.",
        "passenger_mood": "귀찮아함, 비용 걱정",
        "passenger_persona": "20대 여성, 소중한 물건이 들어있어서 위탁 꺼림",
        "escalation_triggers": ["무조건 위탁하라고 할 경우", "본인이 알아서 하라고 할 경우"],
        "ideal_response_keywords": ["다른 공간 확인", "소중품 분리 제안", "안전하게 위탁 보장"],
        "evaluation_criteria": {
            "solution": "대안을 찾으려 했는가",
            "understanding": "승객의 우려를 이해했는가",
            "reassurance": "위탁 시 안전을 보장했는가",
        },
    },
    "seatbelt_refuse": {
        "category": "안전/규정",
        "title": "안전벨트 착용 거부",
        "difficulty": 4,
        "situation": "난기류 예보로 안전벨트 착용 사인이 켜졌는데, 한 승객이 '불편하다'며 벨트 착용을 거부합니다.",
        "passenger_mood": "귀찮아함, 반항적",
        "passenger_persona": "40대 남성, 권위에 반항적 성향",
        "escalation_triggers": ["계속 부드럽게만 요청할 경우", "포기할 경우"],
        "ideal_response_keywords": ["안전 강조", "단호한 태도", "법적 결과 언급", "기장 보고"],
        "evaluation_criteria": {
            "firmness": "단호하게 요청했는가",
            "safety": "안전의 중요성을 강조했는가",
            "escalation": "필요시 상급자에게 보고 언급했는가",
        },
    },
    "mask_refuse": {
        "category": "안전/규정",
        "title": "마스크 착용 거부 (감염병 시)",
        "difficulty": 4,
        "situation": "감염병 유행 시기, 한 승객이 마스크 착용을 거부하며 '개인의 자유'라고 주장합니다.",
        "passenger_mood": "확신에 차 있음, 논쟁적",
        "passenger_persona": "50대 남성, 자신의 권리를 강하게 주장",
        "escalation_triggers": ["논쟁에 말려들 경우", "포기할 경우"],
        "ideal_response_keywords": ["다른 승객 안전", "항공사 규정", "단호하지만 정중함", "하기 불가 경고"],
        "evaluation_criteria": {
            "firmness": "원칙을 지켰는가",
            "calm": "침착하게 대응했는가",
            "other_passengers": "다른 승객의 안전을 언급했는가",
        },
    },
    "smoking_lavatory": {
        "category": "안전/규정",
        "title": "화장실에서 흡연 적발",
        "difficulty": 4,
        "situation": "화장실에서 담배 냄새가 나서 확인하니 한 승객이 흡연 중이었습니다.",
        "passenger_mood": "당황, 변명하려 함",
        "passenger_persona": "40대 남성, 장거리 비행 중 니코틴 금단",
        "escalation_triggers": ["가볍게 넘길 경우"],
        "ideal_response_keywords": ["심각성 설명", "법적 처벌 안내", "기장 보고", "단호한 경고"],
        "evaluation_criteria": {
            "seriousness": "심각성을 전달했는가",
            "procedure": "규정에 따라 처리했는가",
            "documentation": "기장에게 보고했는가",
        },
    },
    "standing_during_turbulence": {
        "category": "안전/규정",
        "title": "난기류 중 선반 열려고 함",
        "difficulty": 3,
        "situation": "안전벨트 사인이 켜져 있는데 승객이 선반에서 가방을 꺼내려고 일어섰습니다.",
        "passenger_mood": "급함, 가방에서 뭔가 필요함",
        "passenger_persona": "30대 여성, 약을 먹어야 함",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["즉시 착석 요청", "필요한 것 확인", "대신 가져다주기"],
        "evaluation_criteria": {
            "safety": "즉시 착석을 요청했는가",
            "help": "필요한 것을 대신 가져다줬는가",
            "speed": "신속하게 대응했는가",
        },
    },
    "child_no_seatbelt": {
        "category": "안전/규정",
        "title": "아이가 안전벨트 안 함",
        "difficulty": 2,
        "situation": "이륙 준비 중인데 어린아이가 안전벨트를 하지 않고 있습니다. 부모가 '잠깐이면 되지 않냐'고 합니다.",
        "passenger_mood": "귀찮아함",
        "passenger_persona": "30대 부모, 3살 아이가 보챔",
        "escalation_triggers": ["포기할 경우"],
        "ideal_response_keywords": ["안전 강조", "도움 제안", "아이용 벨트 제공", "단호함"],
        "evaluation_criteria": {
            "firmness": "규정을 지켰는가",
            "help": "벨트 착용을 도왔는가",
            "manner": "정중하게 요청했는가",
        },
    },
    "aisle_obstruction": {
        "category": "안전/규정",
        "title": "통로에 가방 방치",
        "difficulty": 1,
        "situation": "승객이 발 아래 공간이 부족하다며 가방을 통로에 놓았습니다.",
        "passenger_mood": "불편함",
        "passenger_persona": "50대 여성, 가방이 큼",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["안전 이유 설명", "다른 공간 찾기", "정중한 요청"],
        "evaluation_criteria": {
            "safety": "통로 안전을 설명했는가",
            "solution": "대안 공간을 찾았는가",
            "manner": "정중하게 요청했는가",
        },
    },
    "photo_cockpit": {
        "category": "안전/규정",
        "title": "조종실 사진 찍으려 함",
        "difficulty": 3,
        "situation": "승객이 조종실 문 앞에서 사진을 찍으려고 합니다.",
        "passenger_mood": "호기심, 기념촬영 원함",
        "passenger_persona": "20대 남성, 비행기 덕후",
        "escalation_triggers": ["강하게 제지할 경우"],
        "ideal_response_keywords": ["보안 규정 설명", "정중한 제지", "다른 포토존 안내"],
        "evaluation_criteria": {
            "security": "보안 규정을 설명했는가",
            "manner": "정중하게 제지했는가",
            "alternative": "다른 사진 장소를 안내했는가",
        },
    },
    "emergency_exit_operation": {
        "category": "안전/규정",
        "title": "비상구 작동법 거부",
        "difficulty": 3,
        "situation": "비상구 좌석 승객에게 비상 시 문 개방 동의를 받아야 하는데 '그런 거 하기 싫다'고 합니다.",
        "passenger_mood": "귀찮음",
        "passenger_persona": "30대 남성, 그냥 넓은 자리라 선택함",
        "escalation_triggers": ["강요할 경우"],
        "ideal_response_keywords": ["중요성 설명", "다른 좌석 제안", "정중한 설득"],
        "evaluation_criteria": {
            "explanation": "비상구 역할을 설명했는가",
            "solution": "좌석 변경을 제안했는가",
            "persistence": "끝까지 설득했는가",
        },
    },
    "landing_electronic": {
        "category": "안전/규정",
        "title": "착륙 중 게임기 사용",
        "difficulty": 2,
        "situation": "착륙 준비 중인데 아이가 게임기를 끄지 않습니다. 부모도 그냥 두고 있습니다.",
        "passenger_mood": "아이가 떼씀",
        "passenger_persona": "8살 아이와 30대 부모",
        "escalation_triggers": ["포기할 경우"],
        "ideal_response_keywords": ["아이 눈높이 대화", "착륙 후 다시 할 수 있다고 설명", "부모에게도 요청"],
        "evaluation_criteria": {
            "approach": "아이에게 적절히 접근했는가",
            "parents": "부모에게도 협조를 구했는가",
            "success": "결국 끄게 했는가",
        },
    },
    "unauthorized_seat_change": {
        "category": "안전/규정",
        "title": "무단 좌석 이동 (이륙 후)",
        "difficulty": 2,
        "situation": "이륙 후 승객이 빈자리로 무단 이동해 앉아있습니다. 그 자리는 밸런스상 비워둔 좌석입니다.",
        "passenger_mood": "편하게 쉬고 싶음",
        "passenger_persona": "40대 남성, 옆자리가 비어서 눕고 싶음",
        "escalation_triggers": ["강압적으로 이동시킬 경우"],
        "ideal_response_keywords": ["안전 이유 설명", "무게 배분 설명", "정중한 요청"],
        "evaluation_criteria": {
            "explanation": "이유를 명확히 설명했는가",
            "manner": "정중하게 요청했는가",
            "firmness": "원칙을 지켰는가",
        },
    },
    "door_touch": {
        "category": "안전/규정",
        "title": "비상문을 만지고 있음",
        "difficulty": 4,
        "situation": "승객이 비상구 문에 손을 대고 이것저것 만지고 있습니다.",
        "passenger_mood": "호기심, 또는 술 취함",
        "passenger_persona": "30대 남성, 약간 취한 상태",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["즉시 제지", "심각성 설명", "기장 보고 고려"],
        "evaluation_criteria": {
            "immediate": "즉시 제지했는가",
            "seriousness": "심각성을 전달했는가",
            "report": "상황을 보고했는가",
        },
    },
    "life_vest_play": {
        "category": "안전/규정",
        "title": "아이가 구명조끼 가지고 놀음",
        "difficulty": 2,
        "situation": "아이가 좌석 아래 구명조끼를 꺼내서 가지고 놀고 있습니다.",
        "passenger_mood": "아이는 재미있어함",
        "passenger_persona": "6살 남아, 부모는 자고 있음",
        "escalation_triggers": ["부모를 깨워 혼내게 할 경우"],
        "ideal_response_keywords": ["부드럽게 제지", "위험성 설명", "다른 놀이 제안", "부모에게 살짝 알림"],
        "evaluation_criteria": {
            "approach": "아이에게 부드럽게 접근했는가",
            "safety": "구명조끼의 중요성을 설명했는가",
            "parents": "부모에게 적절히 알렸는가",
        },
    },

    # ========== 불만/컴플레인 (15개) ==========
    "delay_angry": {
        "category": "불만/컴플레인",
        "title": "3시간 지연에 화난 승객",
        "difficulty": 3,
        "situation": "항공기 정비로 3시간 지연되었습니다. 중요한 미팅에 늦게 된 승객이 화를 내며 보상을 요구합니다.",
        "passenger_mood": "매우 화남, 좌절감",
        "passenger_persona": "40대 사업가, 계약 미팅에 늦게 됨",
        "escalation_triggers": ["항공사 잘못이 아니라고 할 경우", "공감 없이 규정만 말할 경우"],
        "ideal_response_keywords": ["진심 어린 사과", "공감 표현", "정보 제공", "가능한 지원 안내"],
        "evaluation_criteria": {
            "empathy": "승객의 상황에 공감했는가",
            "apology": "진심으로 사과했는가",
            "information": "정확한 정보를 제공했는가",
        },
    },
    "luggage_damage": {
        "category": "불만/컴플레인",
        "title": "수하물 파손",
        "difficulty": 3,
        "situation": "수하물 수취대에서 가방이 파손된 것을 발견한 승객이 화를 내며 항의합니다.",
        "passenger_mood": "화남, 당황함",
        "passenger_persona": "30대 여성, 새로 산 고가 캐리어가 파손됨",
        "escalation_triggers": ["책임 회피할 경우", "절차만 안내하고 공감 없을 경우"],
        "ideal_response_keywords": ["사과", "공감", "신고 절차 안내", "신속한 처리 약속"],
        "evaluation_criteria": {
            "empathy": "승객의 속상함에 공감했는가",
            "procedure": "명확한 절차를 안내했는가",
            "support": "적극적으로 도우려 했는가",
        },
    },
    "slow_service": {
        "category": "불만/컴플레인",
        "title": "서비스가 너무 느리다",
        "difficulty": 2,
        "situation": "식사 서비스가 늦어져 한 승객이 '왜 이렇게 느리냐'며 짜증을 냅니다.",
        "passenger_mood": "배고프고 짜증남",
        "passenger_persona": "30대 직장인, 아침을 못 먹어서 매우 배고픔",
        "escalation_triggers": ["변명할 경우", "무시하는 태도"],
        "ideal_response_keywords": ["사과", "빠른 서비스 약속", "간식 제공 제안"],
        "evaluation_criteria": {
            "apology": "서비스 지연에 사과했는가",
            "quick_action": "빠른 조치를 취했는가",
            "care": "승객을 배려하는 태도를 보였는가",
        },
    },
    "vip_treatment": {
        "category": "불만/컴플레인",
        "title": "VIP인데 대우가 별로다",
        "difficulty": 3,
        "situation": "항공사 최상위 등급 회원이 '예전보다 서비스가 나빠졌다'며 불만을 표시합니다.",
        "passenger_mood": "실망함, 서운함",
        "passenger_persona": "50대 사업가, 연간 100회 이상 탑승하는 VIP",
        "escalation_triggers": ["가볍게 넘길 경우", "변명할 경우"],
        "ideal_response_keywords": ["감사 표현", "경청", "피드백 수용", "개선 약속", "특별 서비스 제공"],
        "evaluation_criteria": {
            "gratitude": "충성 고객에게 감사를 표했는가",
            "listening": "불만을 경청했는가",
            "action": "개선 또는 추가 서비스를 제안했는가",
        },
    },
    "sns_threat": {
        "category": "불만/컴플레인",
        "title": "SNS에 올리겠다 협박",
        "difficulty": 4,
        "situation": "사소한 서비스 불만으로 승객이 '이거 다 SNS에 올릴 거야'라며 협박조로 말합니다.",
        "passenger_mood": "화남, 과시적",
        "passenger_persona": "20대, 인플루언서라고 주장, 팔로워 많다고 함",
        "escalation_triggers": ["위협에 굴복할 경우", "맞서 싸울 경우"],
        "ideal_response_keywords": ["침착함 유지", "진심 어린 사과", "문제 해결 집중", "협박에 휘둘리지 않음"],
        "evaluation_criteria": {
            "calm": "침착하게 대응했는가",
            "focus": "문제 해결에 집중했는가",
            "professionalism": "협박에 휘둘리지 않았는가",
        },
    },
    "wrong_destination": {
        "category": "불만/컴플레인",
        "title": "목적지가 다르다고 주장",
        "difficulty": 3,
        "situation": "승객이 자신은 다른 도시로 가는 비행기인 줄 알았다며 당황하고 화를 냅니다.",
        "passenger_mood": "패닉, 화남",
        "passenger_persona": "60대 여성, 여행사 통해 예약, 티켓 잘 못 봄",
        "escalation_triggers": ["본인 잘못이라고 할 경우"],
        "ideal_response_keywords": ["침착하게 확인", "공감", "가능한 해결책 모색", "도착 후 지원 안내"],
        "evaluation_criteria": {
            "calm": "침착하게 대응했는가",
            "empathy": "당황스러움에 공감했는가",
            "solution": "해결책을 모색했는가",
        },
    },
    "crew_attitude": {
        "category": "불만/컴플레인",
        "title": "승무원 태도 불만",
        "difficulty": 3,
        "situation": "승객이 '아까 그 승무원 태도가 너무 불친절했다'며 불만을 제기합니다.",
        "passenger_mood": "불쾌함, 억울함",
        "passenger_persona": "40대 여성, 서비스업 경력자라 민감함",
        "escalation_triggers": ["변명하거나 두둔할 경우"],
        "ideal_response_keywords": ["사과", "경청", "피드백 전달 약속", "추가 서비스 제안"],
        "evaluation_criteria": {
            "apology": "동료를 대신해 사과했는가",
            "listening": "끝까지 경청했는가",
            "action": "개선 조치를 약속했는가",
        },
    },
    "overbooking": {
        "category": "불만/컴플레인",
        "title": "오버부킹으로 좌석 없음",
        "difficulty": 4,
        "situation": "체크인을 했는데 오버부킹으로 좌석이 없다고 합니다. 승객이 매우 화가 났습니다.",
        "passenger_mood": "분노, 황당함",
        "passenger_persona": "30대 직장인, 중요한 출장",
        "escalation_triggers": ["사과 없이 규정만 말할 경우"],
        "ideal_response_keywords": ["진심 어린 사과", "보상 안내", "대체편 마련", "우선 처리"],
        "evaluation_criteria": {
            "apology": "진심으로 사과했는가",
            "compensation": "적절한 보상을 안내했는가",
            "solution": "대체 방안을 제시했는가",
        },
    },
    "boarding_denied": {
        "category": "불만/컴플레인",
        "title": "탑승 거부 불만 (체크인 늦음)",
        "difficulty": 3,
        "situation": "체크인 마감 후 도착한 승객이 '5분 늦었을 뿐인데 왜 못 타냐'며 화를 냅니다.",
        "passenger_mood": "급함, 화남",
        "passenger_persona": "40대 사업가, 택시가 막혔다고 함",
        "escalation_triggers": ["규정만 말할 경우"],
        "ideal_response_keywords": ["공감", "다음 편 안내", "가능한 지원", "정중한 설명"],
        "evaluation_criteria": {
            "empathy": "상황에 공감했는가",
            "solution": "대안을 제시했는가",
            "manner": "정중하게 응대했는가",
        },
    },
    "connection_missed": {
        "category": "불만/컴플레인",
        "title": "연결편 놓침",
        "difficulty": 3,
        "situation": "항공기 지연으로 연결편을 놓친 승객이 '어떻게 해줄 거냐'며 따집니다.",
        "passenger_mood": "좌절, 화남",
        "passenger_persona": "20대 여성, 배낭여행 중",
        "escalation_triggers": ["도와줄 수 없다고 할 경우"],
        "ideal_response_keywords": ["사과", "다음 연결편 확인", "항공사 지원 안내", "숙박 지원 언급"],
        "evaluation_criteria": {
            "apology": "사과했는가",
            "solution": "대안을 찾았는가",
            "support": "지원 내용을 안내했는가",
        },
    },
    "no_upgrade_miles": {
        "category": "불만/컴플레인",
        "title": "마일리지 업그레이드 안 됨",
        "difficulty": 2,
        "situation": "마일리지로 업그레이드하려 했는데 좌석이 없다며 화를 냅니다.",
        "passenger_mood": "실망, 억울함",
        "passenger_persona": "50대 남성, 마일리지 많이 모음",
        "escalation_triggers": ["어쩔 수 없다고만 할 경우"],
        "ideal_response_keywords": ["공감", "상황 설명", "다음 기회 안내", "다른 혜택 제안"],
        "evaluation_criteria": {
            "empathy": "실망감을 이해했는가",
            "explanation": "상황을 설명했는가",
            "alternative": "다른 혜택을 제안했는가",
        },
    },
    "lounge_denied": {
        "category": "불만/컴플레인",
        "title": "라운지 이용 거부됨",
        "difficulty": 2,
        "situation": "라운지를 이용하려 했는데 자격이 안 된다고 거부당한 승객이 불만입니다.",
        "passenger_mood": "당황, 창피함",
        "passenger_persona": "30대 여성, 친구가 된다고 해서 따라감",
        "escalation_triggers": ["창피를 줄 경우"],
        "ideal_response_keywords": ["정중한 설명", "자격 조건 안내", "유료 이용 안내", "배려"],
        "evaluation_criteria": {
            "manner": "정중하게 설명했는가",
            "information": "자격 조건을 안내했는가",
            "dignity": "자존심을 배려했는가",
        },
    },
    "pet_complaint": {
        "category": "불만/컴플레인",
        "title": "옆자리 반려동물 불만",
        "difficulty": 2,
        "situation": "옆자리 승객의 반려견이 계속 짖어서 시끄럽다고 불만을 제기합니다.",
        "passenger_mood": "짜증남",
        "passenger_persona": "40대 남성, 일하려고 했는데 집중이 안 됨",
        "escalation_triggers": ["한쪽 편만 들 경우"],
        "ideal_response_keywords": ["양측 배려", "반려동물 주인에게 요청", "좌석 이동 제안", "귀마개 제공"],
        "evaluation_criteria": {
            "balance": "양측을 배려했는가",
            "solution": "해결책을 제시했는가",
            "calm": "상황을 진정시켰는가",
        },
    },
    "no_korean_crew": {
        "category": "불만/컴플레인",
        "title": "한국인 승무원이 없다",
        "difficulty": 2,
        "situation": "외국 항공사인데 한국인 승무원이 없어서 의사소통이 힘들다고 불만입니다.",
        "passenger_mood": "답답함",
        "passenger_persona": "70대 할머니, 영어 전혀 못함",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["공감", "최대한 도움 약속", "번역 앱 활용", "자주 확인 약속"],
        "evaluation_criteria": {
            "empathy": "불편함을 이해했는가",
            "effort": "도우려 노력했는가",
            "follow_up": "지속적으로 신경 썼는가",
        },
    },
    "wrong_class_service": {
        "category": "불만/컴플레인",
        "title": "비즈니스석인데 서비스가 별로",
        "difficulty": 3,
        "situation": "비즈니스석 승객이 '이 가격 내고 이 서비스냐'며 불만을 표시합니다.",
        "passenger_mood": "실망, 화남",
        "passenger_persona": "50대 여성, 기대가 컸음",
        "escalation_triggers": ["변명할 경우", "무시할 경우"],
        "ideal_response_keywords": ["사과", "경청", "개선 약속", "추가 서비스 제공"],
        "evaluation_criteria": {
            "apology": "사과했는가",
            "listening": "경청했는가",
            "action": "보상 서비스를 제공했는가",
        },
    },

    # ========== 의료/응급 (15개) ==========
    "passenger_collapse": {
        "category": "의료/응급",
        "title": "승객이 갑자기 쓰러짐",
        "difficulty": 4,
        "situation": "비행 중 한 승객이 갑자기 의식을 잃고 쓰러졌습니다. 주변 승객들이 놀라고 있습니다.",
        "passenger_mood": "의식 없음 (주변 승객들 공포)",
        "passenger_persona": "70대 남성, 심장병 병력 있음 (동행인 정보)",
        "escalation_triggers": ["당황해서 우왕좌왕할 경우"],
        "ideal_response_keywords": ["침착한 대응", "의료진 호출", "AED 준비", "기장 보고", "주변 승객 안정"],
        "evaluation_criteria": {
            "calm": "침착하게 대응했는가",
            "procedure": "응급 절차를 따랐는가",
            "coordination": "팀과 협력했는가",
        },
    },
    "child_fever": {
        "category": "의료/응급",
        "title": "아이가 고열",
        "difficulty": 3,
        "situation": "3살 아이의 엄마가 아이가 갑자기 열이 많이 난다며 도움을 요청합니다.",
        "passenger_mood": "불안하고 걱정됨",
        "passenger_persona": "30대 엄마, 아이 첫 해외여행 중",
        "escalation_triggers": ["가볍게 여길 경우", "아무 조치도 안 할 경우"],
        "ideal_response_keywords": ["안심시키기", "해열제 제공", "의료진 확인", "체온 체크", "물 제공"],
        "evaluation_criteria": {
            "care": "아이와 엄마를 배려했는가",
            "action": "적절한 조치를 취했는가",
            "reassurance": "엄마를 안심시켰는가",
        },
    },
    "panic_attack": {
        "category": "의료/응급",
        "title": "공황장애 승객",
        "difficulty": 3,
        "situation": "한 승객이 갑자기 숨을 가쁘게 쉬며 '죽을 것 같다'고 호소합니다. 공황발작으로 보입니다.",
        "passenger_mood": "극도의 공포, 호흡 곤란",
        "passenger_persona": "20대 여성, 비행 공포증 있음",
        "escalation_triggers": ["무시하거나 가볍게 여길 경우"],
        "ideal_response_keywords": ["차분한 목소리", "함께 호흡", "안심시키기", "조용한 공간", "물 제공"],
        "evaluation_criteria": {
            "calm": "차분하게 대응했는가",
            "empathy": "승객의 공포에 공감했는가",
            "technique": "적절한 진정 기법을 사용했는가",
        },
    },
    "pregnant_pain": {
        "category": "의료/응급",
        "title": "임산부 복통 호소",
        "difficulty": 4,
        "situation": "임신 7개월 승객이 갑자기 복통을 호소하며 고통스러워합니다.",
        "passenger_mood": "공포, 고통",
        "passenger_persona": "30대 임산부, 남편과 함께 탑승",
        "escalation_triggers": ["당황해서 아무것도 못 할 경우"],
        "ideal_response_keywords": ["침착", "눕히기", "의료진 호출", "기장 보고", "비상착륙 고려", "남편 안심"],
        "evaluation_criteria": {
            "urgency": "상황의 긴급성을 인지했는가",
            "procedure": "적절한 응급 절차를 따랐는가",
            "communication": "기장에게 보고했는가",
        },
    },
    "elderly_breathing": {
        "category": "의료/응급",
        "title": "노인 승객 호흡 곤란",
        "difficulty": 4,
        "situation": "80대 노인 승객이 호흡이 힘들다며 가슴을 움켜쥐고 있습니다.",
        "passenger_mood": "고통스러움",
        "passenger_persona": "80대 남성, 혼자 탑승, 천식 병력",
        "escalation_triggers": ["늦게 대응할 경우"],
        "ideal_response_keywords": ["산소 공급", "의료진 호출", "침착", "기장 보고", "약 소지 확인"],
        "evaluation_criteria": {
            "speed": "신속하게 대응했는가",
            "procedure": "응급 절차를 따랐는가",
            "equipment": "필요한 장비를 준비했는가",
        },
    },
    "diabetic_emergency": {
        "category": "의료/응급",
        "title": "당뇨 환자 저혈당",
        "difficulty": 3,
        "situation": "승객이 갑자기 식은땀을 흘리며 손을 떨고 있습니다. 당뇨 환자라고 합니다.",
        "passenger_mood": "힘없음, 혼란",
        "passenger_persona": "50대 남성, 식사를 못 해서 저혈당 상태",
        "escalation_triggers": ["늦게 대응할 경우"],
        "ideal_response_keywords": ["당분 제공", "주스/사탕", "눕히기", "상태 관찰"],
        "evaluation_criteria": {
            "knowledge": "저혈당 대처법을 알았는가",
            "speed": "빠르게 당분을 제공했는가",
            "care": "상태를 지속 관찰했는가",
        },
    },
    "nosebleed": {
        "category": "의료/응급",
        "title": "코피가 멈추지 않음",
        "difficulty": 2,
        "situation": "승객의 코피가 15분째 멈추지 않고 있습니다.",
        "passenger_mood": "당황, 걱정됨",
        "passenger_persona": "30대 여성, 건조한 기내에서 코피 남",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["휴지/거즈 제공", "머리 숙이게", "코 눌러주기", "상태 관찰"],
        "evaluation_criteria": {
            "knowledge": "응급처치법을 알았는가",
            "action": "적절한 조치를 취했는가",
            "care": "상태를 관찰했는가",
        },
    },
    "food_choking": {
        "category": "의료/응급",
        "title": "음식이 목에 걸림",
        "difficulty": 4,
        "situation": "승객이 기내식을 먹다가 갑자기 목을 감싸며 기침을 합니다. 질식 상황입니다.",
        "passenger_mood": "공포, 숨 못 쉼",
        "passenger_persona": "60대 남성",
        "escalation_triggers": ["늦게 대응할 경우"],
        "ideal_response_keywords": ["하임리히법", "등 두드리기", "의료진 호출", "침착한 대응"],
        "evaluation_criteria": {
            "knowledge": "하임리히법을 알았는가",
            "speed": "즉시 대응했는가",
            "calm": "침착하게 처리했는가",
        },
    },
    "seizure": {
        "category": "의료/응급",
        "title": "경련/발작 승객",
        "difficulty": 4,
        "situation": "승객이 갑자기 경련을 일으키며 쓰러졌습니다. 간질 발작으로 보입니다.",
        "passenger_mood": "의식 혼미",
        "passenger_persona": "40대 남성, 간질 병력 (동행인 정보)",
        "escalation_triggers": ["잘못된 조치를 할 경우"],
        "ideal_response_keywords": ["안전한 공간 확보", "억지로 잡지 않기", "머리 보호", "기도 확보", "시간 체크"],
        "evaluation_criteria": {
            "knowledge": "발작 대처법을 알았는가",
            "safety": "승객을 안전하게 했는가",
            "calm": "침착하게 대응했는가",
        },
    },
    "ear_pain": {
        "category": "의료/응급",
        "title": "귀가 아파서 우는 아이",
        "difficulty": 2,
        "situation": "착륙 중 아이가 귀가 아프다며 울고 있습니다. 기압 변화 때문입니다.",
        "passenger_mood": "통증, 울음",
        "passenger_persona": "4살 여아, 첫 비행",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["사탕/껌 제공", "하품 유도", "코 풀기 안내", "엄마 안심"],
        "evaluation_criteria": {
            "knowledge": "기압 통증 해소법을 알았는가",
            "care": "아이를 돌봤는가",
            "empathy": "엄마를 안심시켰는가",
        },
    },
    "motion_sickness": {
        "category": "의료/응급",
        "title": "심한 멀미",
        "difficulty": 2,
        "situation": "승객이 심하게 멀미를 하며 토할 것 같다고 합니다. 얼굴이 창백합니다.",
        "passenger_mood": "메스꺼움, 힘없음",
        "passenger_persona": "20대 여성, 난기류로 멀미 심해짐",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["봉투 제공", "찬 물/얼음", "눕히기", "환기", "멀미약"],
        "evaluation_criteria": {
            "speed": "빠르게 대응했는가",
            "care": "편하게 해주었는가",
            "supply": "필요한 물품을 제공했는가",
        },
    },
    "anxiety_flying": {
        "category": "의료/응급",
        "title": "비행 공포증",
        "difficulty": 2,
        "situation": "이륙 전 승객이 손을 떨며 무섭다고 합니다. 비행 공포증이 있다고 합니다.",
        "passenger_mood": "두려움, 긴장",
        "passenger_persona": "30대 여성, 어쩔 수 없이 비행기 탐",
        "escalation_triggers": ["무시할 경우", "괜찮다고만 할 경우"],
        "ideal_response_keywords": ["안심시키기", "함께 대화", "안전 정보 제공", "물 제공", "지속 관심"],
        "evaluation_criteria": {
            "empathy": "공포에 공감했는가",
            "calm": "차분하게 안심시켰는가",
            "care": "지속적으로 신경 썼는가",
        },
    },
    "cut_injury": {
        "category": "의료/응급",
        "title": "손 베임 (유리잔)",
        "difficulty": 2,
        "situation": "유리잔이 깨지면서 승객이 손을 베었습니다. 피가 나고 있습니다.",
        "passenger_mood": "당황, 아픔",
        "passenger_persona": "40대 여성",
        "escalation_triggers": ["늦게 대응할 경우"],
        "ideal_response_keywords": ["응급키트", "소독", "반창고/붕대", "상처 확인"],
        "evaluation_criteria": {
            "speed": "빠르게 대응했는가",
            "treatment": "응급처치를 했는가",
            "care": "상태를 확인했는가",
        },
    },
    "drunk_unwell": {
        "category": "의료/응급",
        "title": "술 마시고 기절",
        "difficulty": 3,
        "situation": "술을 많이 마신 승객이 축 늘어져 반응이 없습니다.",
        "passenger_mood": "의식 저하",
        "passenger_persona": "30대 남성, 많이 취함",
        "escalation_triggers": ["방치할 경우"],
        "ideal_response_keywords": ["의식 확인", "회복자세", "기도 확보", "상태 관찰", "기장 보고"],
        "evaluation_criteria": {
            "assessment": "상태를 정확히 파악했는가",
            "position": "안전한 자세를 취하게 했는가",
            "monitoring": "지속 관찰했는가",
        },
    },
    "headache_severe": {
        "category": "의료/응급",
        "title": "극심한 두통",
        "difficulty": 3,
        "situation": "승객이 극심한 두통을 호소합니다. 구토까지 하고 있습니다.",
        "passenger_mood": "고통",
        "passenger_persona": "50대 여성, 고혈압 병력",
        "escalation_triggers": ["가볍게 여길 경우"],
        "ideal_response_keywords": ["진통제", "눕히기", "의료진 호출", "혈압 확인", "기장 보고 고려"],
        "evaluation_criteria": {
            "seriousness": "심각성을 인지했는가",
            "action": "적절한 조치를 취했는가",
            "escalation": "필요시 상위 보고를 했는가",
        },
    },

    # ========== 특수 승객 (15개) ==========
    "unaccompanied_minor_crying": {
        "category": "특수 승객",
        "title": "혼자 탄 어린이 울음",
        "difficulty": 2,
        "situation": "비동반 소아(10살)가 엄마가 보고 싶다며 울고 있습니다.",
        "passenger_mood": "외롭고 무서움",
        "passenger_persona": "10살 남자아이, 처음으로 혼자 비행",
        "escalation_triggers": ["무시할 경우", "어른처럼 대할 경우"],
        "ideal_response_keywords": ["눈높이 대화", "안심시키기", "간식/음료 제공", "관심 보여주기"],
        "evaluation_criteria": {
            "empathy": "아이의 감정에 공감했는가",
            "approach": "아이 눈높이에서 대화했는가",
            "care": "지속적으로 관심을 보였는가",
        },
    },
    "wheelchair_restroom": {
        "category": "특수 승객",
        "title": "휠체어 승객 화장실",
        "difficulty": 2,
        "situation": "휠체어 승객이 화장실을 이용하고 싶다며 도움을 요청합니다.",
        "passenger_mood": "불편하지만 참고 있음",
        "passenger_persona": "50대 남성, 하반신 마비",
        "escalation_triggers": ["민망하게 만들 경우", "도움 없이 혼자 하라고 할 경우"],
        "ideal_response_keywords": ["존중", "프라이버시 배려", "적극적 도움", "자연스럽게"],
        "evaluation_criteria": {
            "respect": "승객의 존엄성을 지켰는가",
            "help": "적극적으로 도왔는가",
            "privacy": "프라이버시를 배려했는가",
        },
    },
    "blind_passenger": {
        "category": "특수 승객",
        "title": "시각장애인 안내",
        "difficulty": 2,
        "situation": "시각장애인 승객이 좌석과 주변 환경에 대한 설명을 요청합니다.",
        "passenger_mood": "도움이 필요함",
        "passenger_persona": "40대 여성, 선천적 시각장애, 자주 혼자 여행",
        "escalation_triggers": ["대충 설명할 경우", "불편해할 경우"],
        "ideal_response_keywords": ["상세한 설명", "손 위치 안내", "서비스 타이밍 알림", "존중하는 태도"],
        "evaluation_criteria": {
            "detail": "충분히 상세하게 설명했는가",
            "respect": "존중하는 태도를 보였는가",
            "proactive": "필요한 것을 먼저 제안했는가",
        },
    },
    "first_flight_elderly": {
        "category": "특수 승객",
        "title": "처음 비행기 타는 노인",
        "difficulty": 1,
        "situation": "70대 노인 승객이 처음 비행기를 타서 모든 것이 낯설고 불안해합니다.",
        "passenger_mood": "불안하고 긴장됨",
        "passenger_persona": "70대 할머니, 손주 보러 혼자 여행",
        "escalation_triggers": ["귀찮아할 경우"],
        "ideal_response_keywords": ["친절한 안내", "안전벨트 도움", "안심시키기", "지속적 관심"],
        "evaluation_criteria": {
            "patience": "인내심을 보였는가",
            "kindness": "친절하게 안내했는가",
            "care": "지속적으로 신경 썼는가",
        },
    },
    "language_barrier": {
        "category": "특수 승객",
        "title": "외국인 언어 소통 불가",
        "difficulty": 3,
        "situation": "영어도 한국어도 못하는 외국인 승객이 무언가를 급하게 요청하지만 소통이 안 됩니다.",
        "passenger_mood": "답답함, 급함",
        "passenger_persona": "중년 아랍 여성, 아랍어만 가능",
        "escalation_triggers": ["포기할 경우", "짜증낼 경우"],
        "ideal_response_keywords": ["번역 앱 활용", "그림/제스처", "인내심", "다른 승객 도움 요청"],
        "evaluation_criteria": {
            "creativity": "창의적 소통 방법을 시도했는가",
            "patience": "인내심을 보였는가",
            "effort": "해결하려 노력했는가",
        },
    },
    "deaf_passenger": {
        "category": "특수 승객",
        "title": "청각장애인 안내",
        "difficulty": 2,
        "situation": "청각장애인 승객이 기내 안내방송을 듣지 못해 무슨 일인지 불안해합니다.",
        "passenger_mood": "불안, 소외감",
        "passenger_persona": "30대 남성, 선천적 청각장애",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["필담", "제스처", "개별 안내", "지속적 관심"],
        "evaluation_criteria": {
            "communication": "효과적으로 소통했는가",
            "care": "지속적으로 신경 썼는가",
            "inclusion": "소외감을 느끼지 않게 했는가",
        },
    },
    "autism_child": {
        "category": "특수 승객",
        "title": "자폐 스펙트럼 아동",
        "difficulty": 3,
        "situation": "자폐 스펙트럼 아이가 낯선 환경에 불안해하며 소리를 지르고 있습니다. 부모가 미안해합니다.",
        "passenger_mood": "아이: 불안 / 부모: 미안함",
        "passenger_persona": "8살 남아, 부모와 함께",
        "escalation_triggers": ["짜증을 낼 경우", "다른 승객에게 사과하라고 할 경우"],
        "ideal_response_keywords": ["이해", "조용한 공간 제안", "부모 위로", "다른 승객 양해 구하기"],
        "evaluation_criteria": {
            "understanding": "상황을 이해했는가",
            "support": "부모를 지지했는가",
            "solution": "해결책을 제시했는가",
        },
    },
    "celebrity_passenger": {
        "category": "특수 승객",
        "title": "유명인 승객",
        "difficulty": 2,
        "situation": "유명 연예인이 탑승했습니다. 다른 승객들이 사진을 찍으려 합니다.",
        "passenger_mood": "프라이버시 원함",
        "passenger_persona": "유명 가수, 조용히 여행하고 싶음",
        "escalation_triggers": ["프라이버시를 안 지켜줄 경우"],
        "ideal_response_keywords": ["프라이버시 보호", "다른 승객 만류", "존중하는 태도"],
        "evaluation_criteria": {
            "privacy": "프라이버시를 보호했는가",
            "discretion": "조용히 처리했는가",
            "balance": "다른 승객도 배려했는가",
        },
    },
    "elderly_dementia": {
        "category": "특수 승객",
        "title": "치매 노인 혼란",
        "difficulty": 3,
        "situation": "혼자 탑승한 노인이 '여기가 어디냐', '집에 가야 한다'며 혼란스러워합니다. 경미한 치매가 의심됩니다.",
        "passenger_mood": "혼란, 불안",
        "passenger_persona": "80대 할머니, 보호자가 목적지에서 기다림",
        "escalation_triggers": ["다그칠 경우", "방치할 경우"],
        "ideal_response_keywords": ["차분하게 안심", "반복 설명", "함께 있어주기", "도착지 연락처 확인"],
        "evaluation_criteria": {
            "patience": "인내심을 보였는가",
            "calm": "차분하게 대응했는가",
            "care": "지속적으로 돌봤는가",
        },
    },
    "service_animal": {
        "category": "특수 승객",
        "title": "안내견 동반 승객",
        "difficulty": 2,
        "situation": "시각장애인 승객이 안내견과 함께 탑승했습니다. 옆 승객이 개가 무섭다고 합니다.",
        "passenger_mood": "양측 불편",
        "passenger_persona": "시각장애인 40대 남성 + 옆자리 30대 여성",
        "escalation_triggers": ["한쪽 편만 들 경우"],
        "ideal_response_keywords": ["안내견 중요성 설명", "좌석 이동 제안", "양측 배려"],
        "evaluation_criteria": {
            "education": "안내견 역할을 설명했는가",
            "solution": "대안을 제시했는가",
            "balance": "양측을 배려했는가",
        },
    },
    "nervous_first_timer": {
        "category": "특수 승객",
        "title": "첫 해외여행 긴장",
        "difficulty": 1,
        "situation": "첫 해외여행으로 모든 것이 불안한 승객이 계속 질문을 합니다.",
        "passenger_mood": "긴장, 불안",
        "passenger_persona": "20대 여성, 혼자 첫 해외여행",
        "escalation_triggers": ["귀찮아할 경우"],
        "ideal_response_keywords": ["친절한 안내", "안심시키기", "필요한 정보 제공", "격려"],
        "evaluation_criteria": {
            "patience": "인내심을 보였는가",
            "kindness": "친절하게 대했는가",
            "encouragement": "용기를 줬는가",
        },
    },
    "plus_size_passenger": {
        "category": "특수 승객",
        "title": "체격이 큰 승객 좌석 문제",
        "difficulty": 3,
        "situation": "체격이 큰 승객이 좌석에 불편해 보입니다. 옆 승객이 공간이 좁다고 불만입니다.",
        "passenger_mood": "양측 불편, 창피함",
        "passenger_persona": "체격 큰 40대 남성 + 옆자리 30대 여성",
        "escalation_triggers": ["창피를 줄 경우", "한쪽 편만 들 경우"],
        "ideal_response_keywords": ["존엄성 배려", "조용히 처리", "가능한 해결책 모색"],
        "evaluation_criteria": {
            "dignity": "존엄성을 지켰는가",
            "discretion": "조용히 처리했는가",
            "solution": "해결책을 찾았는가",
        },
    },
    "religious_needs": {
        "category": "특수 승객",
        "title": "종교 의식 공간 요청",
        "difficulty": 2,
        "situation": "무슬림 승객이 기도할 공간을 요청합니다.",
        "passenger_mood": "종교적 필요",
        "passenger_persona": "30대 남성, 기도 시간이 됨",
        "escalation_triggers": ["거부할 경우", "이상하게 볼 경우"],
        "ideal_response_keywords": ["존중", "가능한 공간 안내", "서비스 중 방해 없게"],
        "evaluation_criteria": {
            "respect": "종교를 존중했는가",
            "help": "가능한 도움을 줬는가",
            "understanding": "문화적 이해를 보였는가",
        },
    },
    "returning_soldier": {
        "category": "특수 승객",
        "title": "군인 귀국 (PTSD)",
        "difficulty": 3,
        "situation": "해외 파병에서 돌아오는 군인이 난기류에 매우 민감하게 반응하며 불안해합니다. PTSD가 의심됩니다.",
        "passenger_mood": "극도의 긴장, 과민",
        "passenger_persona": "30대 남성 군인",
        "escalation_triggers": ["무시할 경우", "갑자기 다가갈 경우"],
        "ideal_response_keywords": ["차분한 목소리", "안전 확인", "공간 제공", "이해 표현"],
        "evaluation_criteria": {
            "sensitivity": "민감하게 대응했는가",
            "calm": "차분하게 대했는가",
            "understanding": "상황을 이해했는가",
        },
    },
    "bereaved_passenger": {
        "category": "특수 승객",
        "title": "장례식 가는 승객",
        "difficulty": 2,
        "situation": "승객이 가족 장례식에 가는 중입니다. 울고 있습니다.",
        "passenger_mood": "슬픔, 고통",
        "passenger_persona": "40대 여성, 부모님 장례식",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["위로", "프라이버시", "조용한 배려", "필요한 것 제공"],
        "evaluation_criteria": {
            "empathy": "슬픔에 공감했는가",
            "discretion": "조용히 배려했는가",
            "support": "필요한 도움을 제공했는가",
        },
    },

    # ========== 승객 간 갈등 (15개) ==========
    "reclining_conflict": {
        "category": "승객 간 갈등",
        "title": "리클라이닝 갈등",
        "difficulty": 3,
        "situation": "앞좌석 승객이 좌석을 젖혔는데 뒷좌석 승객이 공간이 없다며 항의합니다. 둘 다 화가 나 있습니다.",
        "passenger_mood": "양측 모두 화남",
        "passenger_persona": "앞: 장거리 피곤한 승객 / 뒤: 키 큰 남성",
        "escalation_triggers": ["한쪽 편만 들 경우"],
        "ideal_response_keywords": ["양측 공감", "중재", "절충안 제시", "식사시간 리클라이닝 규칙"],
        "evaluation_criteria": {
            "neutrality": "중립을 유지했는가",
            "mediation": "효과적으로 중재했는가",
            "solution": "양측이 수용할 수 있는 해결책을 제시했는가",
        },
    },
    "child_noise_complaint": {
        "category": "승객 간 갈등",
        "title": "아이 소음에 옆 승객 항의",
        "difficulty": 3,
        "situation": "3살 아이가 계속 울고 떼를 쓰자 옆 좌석 승객이 '통제 좀 하라'며 부모에게 화를 냅니다.",
        "passenger_mood": "양측 모두 스트레스",
        "passenger_persona": "부모: 지친 30대 부부 / 옆 승객: 피곤한 비즈니스맨",
        "escalation_triggers": ["한쪽 편만 들 경우", "무시할 경우"],
        "ideal_response_keywords": ["양측 공감", "부모 도움 제안", "좌석 이동 제안", "아이 달래기 도움"],
        "evaluation_criteria": {
            "empathy_both": "양측 모두에게 공감했는가",
            "help": "실질적 도움을 제안했는가",
            "calm": "상황을 진정시켰는가",
        },
    },
    "armrest_fight": {
        "category": "승객 간 갈등",
        "title": "팔걸이 싸움",
        "difficulty": 2,
        "situation": "가운데 좌석 승객과 창가 좌석 승객이 팔걸이 사용을 두고 신경전을 벌이고 있습니다.",
        "passenger_mood": "서로 짜증남",
        "passenger_persona": "양측 모두 중년 남성",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["유머 활용", "가운데 좌석 우선 관례 설명", "부드러운 중재"],
        "evaluation_criteria": {
            "diplomacy": "외교적으로 해결했는가",
            "humor": "분위기를 부드럽게 만들었는가",
            "resolution": "문제를 해결했는가",
        },
    },
    "drunk_harassment": {
        "category": "승객 간 갈등",
        "title": "음주 승객이 옆자리 괴롭힘",
        "difficulty": 4,
        "situation": "술에 취한 남성 승객이 옆자리 여성 승객에게 계속 말을 걸며 불편하게 합니다. 여성 승객이 도움을 요청합니다.",
        "passenger_mood": "남성: 취해서 기분 좋음 / 여성: 불안하고 불쾌함",
        "passenger_persona": "남성: 40대 취객 / 여성: 20대 혼자 여행",
        "escalation_triggers": ["가볍게 여길 경우", "조치를 안 할 경우"],
        "ideal_response_keywords": ["여성 승객 보호", "좌석 이동", "남성에게 단호한 경고", "기장 보고"],
        "evaluation_criteria": {
            "protection": "피해 승객을 보호했는가",
            "firmness": "가해자에게 단호했는가",
            "action": "실질적 조치를 취했는가",
        },
    },
    "couple_fight": {
        "category": "승객 간 갈등",
        "title": "커플 싸움",
        "difficulty": 3,
        "situation": "커플로 보이는 두 승객이 작은 목소리로 다투다가 점점 목소리가 커지고 있습니다. 주변 승객들이 불편해합니다.",
        "passenger_mood": "서로 화남, 감정적",
        "passenger_persona": "20대 커플",
        "escalation_triggers": ["공개적으로 개입할 경우", "무시할 경우"],
        "ideal_response_keywords": ["조용히 접근", "음료 제공 핑계", "분리 제안", "프라이버시 배려"],
        "evaluation_criteria": {
            "discretion": "조심스럽게 접근했는가",
            "tact": "상황을 악화시키지 않았는가",
            "resolution": "상황을 진정시켰는가",
        },
    },
    "body_odor_complaint": {
        "category": "승객 간 갈등",
        "title": "옆자리 체취 불만",
        "difficulty": 4,
        "situation": "승객이 옆자리 승객의 체취가 심하다며 자리를 바꿔달라고 합니다.",
        "passenger_mood": "불쾌함",
        "passenger_persona": "30대 여성, 민감한 후각",
        "escalation_triggers": ["상대방에게 직접 말하게 할 경우", "무시할 경우"],
        "ideal_response_keywords": ["조용히 처리", "좌석 이동", "양측 존엄성 보호"],
        "evaluation_criteria": {
            "discretion": "조심스럽게 처리했는가",
            "dignity": "양측 존엄성을 지켰는가",
            "solution": "문제를 해결했는가",
        },
    },
    "photography_conflict": {
        "category": "승객 간 갈등",
        "title": "사진 찍지 말라는 승객",
        "difficulty": 2,
        "situation": "한 승객이 셀카를 찍는데 옆 승객이 자신이 찍히는 것 같다며 화를 냅니다.",
        "passenger_mood": "불쾌함 vs 억울함",
        "passenger_persona": "셀카 찍는 20대 여성 / 옆자리 40대 남성",
        "escalation_triggers": ["한쪽 편만 들 경우"],
        "ideal_response_keywords": ["양측 이해", "사진 확인 부탁", "프라이버시 존중 안내"],
        "evaluation_criteria": {
            "balance": "양측을 배려했는가",
            "privacy": "프라이버시를 강조했는가",
            "resolution": "갈등을 해결했는가",
        },
    },
    "sleeping_leg_space": {
        "category": "승객 간 갈등",
        "title": "다리 뻗어 자는 승객",
        "difficulty": 2,
        "situation": "한 승객이 다리를 앞으로 뻗어 자고 있는데 앞좌석 승객이 발이 닿는다고 불만입니다.",
        "passenger_mood": "불편함",
        "passenger_persona": "자고 있는 20대 남성 / 앞자리 30대 여성",
        "escalation_triggers": ["갑자기 깨울 경우"],
        "ideal_response_keywords": ["조심스럽게 깨우기", "정중히 요청", "양측 배려"],
        "evaluation_criteria": {
            "approach": "조심스럽게 접근했는가",
            "manner": "정중하게 요청했는가",
            "resolution": "문제를 해결했는가",
        },
    },
    "music_loud": {
        "category": "승객 간 갈등",
        "title": "이어폰 소리가 너무 큼",
        "difficulty": 1,
        "situation": "옆 승객의 이어폰에서 음악 소리가 새어나와 시끄럽다고 불만입니다.",
        "passenger_mood": "짜증남",
        "passenger_persona": "음악 듣는 20대 / 옆자리 50대 여성",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["정중히 요청", "볼륨 낮춰달라 부탁", "자연스럽게"],
        "evaluation_criteria": {
            "manner": "정중하게 요청했는가",
            "discretion": "자연스럽게 처리했는가",
            "success": "해결했는가",
        },
    },
    "overhead_bin_fight": {
        "category": "승객 간 갈등",
        "title": "선반 공간 싸움",
        "difficulty": 2,
        "situation": "두 승객이 자기 좌석 위 선반에 먼저 짐을 넣겠다고 다투고 있습니다.",
        "passenger_mood": "양측 화남",
        "passenger_persona": "양측 모두 30대 남성",
        "escalation_triggers": ["한쪽 편만 들 경우"],
        "ideal_response_keywords": ["먼저 온 순서", "다른 공간 제안", "중재"],
        "evaluation_criteria": {
            "fairness": "공정하게 판단했는가",
            "solution": "대안을 제시했는가",
            "calm": "상황을 진정시켰는가",
        },
    },
    "kicking_seat": {
        "category": "승객 간 갈등",
        "title": "뒷좌석에서 의자 차는 아이",
        "difficulty": 3,
        "situation": "아이가 앞좌석을 계속 차는데 앞 승객이 화를 내며 항의합니다.",
        "passenger_mood": "앞 승객: 화남 / 부모: 난감함",
        "passenger_persona": "5살 아이와 부모 / 앞좌석 40대 남성",
        "escalation_triggers": ["한쪽 편만 들 경우"],
        "ideal_response_keywords": ["양측 공감", "부모에게 도움 제안", "앞 승객 위로", "아이 달래기"],
        "evaluation_criteria": {
            "balance": "양측을 배려했는가",
            "help": "실질적 도움을 줬는가",
            "resolution": "상황을 해결했는가",
        },
    },
    "talking_loud": {
        "category": "승객 간 갈등",
        "title": "큰 소리로 대화하는 그룹",
        "difficulty": 2,
        "situation": "친구 그룹이 큰 소리로 떠들고 있어 다른 승객이 불만입니다. 야간 비행입니다.",
        "passenger_mood": "그룹: 신남 / 다른 승객: 피곤함",
        "passenger_persona": "20대 친구 4명 / 불만 승객 50대 여성",
        "escalation_triggers": ["강하게 제지할 경우"],
        "ideal_response_keywords": ["친절히 요청", "야간 비행 안내", "다른 승객 배려 부탁"],
        "evaluation_criteria": {
            "manner": "친절하게 요청했는가",
            "effectiveness": "효과적으로 전달했는가",
            "follow_up": "이후에도 확인했는가",
        },
    },
    "smelly_food": {
        "category": "승객 간 갈등",
        "title": "냄새나는 음식 반입",
        "difficulty": 2,
        "situation": "승객이 가져온 음식 냄새가 강해서 주변 승객들이 불편해합니다.",
        "passenger_mood": "음식 주인: 모름 / 주변: 불쾌",
        "passenger_persona": "음식 가져온 30대 / 주변 여러 승객",
        "escalation_triggers": ["직접적으로 지적할 경우"],
        "ideal_response_keywords": ["조심스럽게 접근", "다 드시면 정리 부탁", "환기"],
        "evaluation_criteria": {
            "discretion": "조심스럽게 처리했는가",
            "solution": "환기 등 조치를 했는가",
            "manner": "정중하게 요청했는가",
        },
    },
    "space_invasion": {
        "category": "승객 간 갈등",
        "title": "옆자리 공간 침범",
        "difficulty": 2,
        "situation": "옆 승객이 팔을 많이 벌리고 앉아서 공간을 침범한다며 불만입니다.",
        "passenger_mood": "불편함",
        "passenger_persona": "침범하는 50대 남성 / 불만인 30대 여성",
        "escalation_triggers": ["한쪽 편만 들 경우"],
        "ideal_response_keywords": ["조용히 중재", "양측 배려", "공간 조정 요청"],
        "evaluation_criteria": {
            "discretion": "조용히 처리했는가",
            "balance": "양측을 배려했는가",
            "resolution": "문제를 해결했는가",
        },
    },
    "queue_jumping": {
        "category": "승객 간 갈등",
        "title": "화장실 새치기",
        "difficulty": 2,
        "situation": "화장실 줄에서 새치기했다며 두 승객이 다투고 있습니다.",
        "passenger_mood": "양측 화남",
        "passenger_persona": "새치기했다는 40대 여성 / 항의하는 30대 남성",
        "escalation_triggers": ["무시할 경우"],
        "ideal_response_keywords": ["양측 의견 청취", "순서 확인", "진정시키기"],
        "evaluation_criteria": {
            "listening": "양측 말을 들었는가",
            "fairness": "공정하게 판단했는가",
            "calm": "상황을 진정시켰는가",
        },
    },
}


def get_scenarios_by_category(category: str) -> list:
    """카테고리별 시나리오 리스트 반환"""
    return [
        {"id": k, **v}
        for k, v in SCENARIOS.items()
        if v["category"] == category
    ]


def get_all_scenarios() -> list:
    """전체 시나리오 리스트 반환"""
    return [{"id": k, **v} for k, v in SCENARIOS.items()]


def get_scenario_by_id(scenario_id: str) -> dict:
    """ID로 시나리오 조회"""
    if scenario_id in SCENARIOS:
        return {"id": scenario_id, **SCENARIOS[scenario_id]}
    return None


def get_scenarios_fresh(category: str = "all", count: int = 1) -> list:
    """
    롤플레잉 시나리오 선택 (중복 방지 적용)
    - 이전에 연습한 시나리오를 제외하고 새 시나리오 우선 선택
    - 모든 시나리오가 소진되면 자동으로 리셋

    Args:
        category: 카테고리명 또는 "all"
        count: 선택할 시나리오 수

    Returns:
        시나리오 리스트 (이전에 안 나온 것 우선)
    """
    import random
    
    # 전체 또는 카테고리별 시나리오 가져오기
    if category == "all":
        all_scenarios = get_all_scenarios()
    else:
        all_scenarios = get_scenarios_by_category(category)
    
    if not all_scenarios:
        return []
    
    try:
        from question_history import get_fresh_roleplay_scenarios
        return get_fresh_roleplay_scenarios(all_scenarios, category, count)
    except ImportError:
        # question_history 모듈 없으면 기존 방식 사용
        return random.sample(all_scenarios, min(count, len(all_scenarios)))
