name: Feature Request
description: Suggest a new feature for FlyReady Lab
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature
      placeholder: Describe the feature in one or two sentences
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should be implemented?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical (Blocking)
        - High (Important)
        - Medium (Nice to have)
        - Low (Wishlist)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Interview Practice
        - AI/ML Features
        - User Interface
        - Performance
        - Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Any mockups, wireframes, or examples?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
